--liquibase formatted sql

--changeSet skryagin:1
CREATE TABLE animal_shelters
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    about          VARCHAR(2047),
    address        VARCHAR(255),
    adoption_rules VARCHAR(2047),
    animal_type    VARCHAR(255),
    contacts       VARCHAR(255),
    opening_hours  VARCHAR(255),
    safety_rules   VARCHAR(2047),
    security_rules VARCHAR(255)
);

CREATE TABLE endpoints
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    content           varchar(2047),
    endpoint_text     VARCHAR(255),
    title             VARCHAR(255),
    animal_shelter_id bigint REFERENCES animal_shelters,
    parent_id         bigint REFERENCES endpoints
);
CREATE TABLE endpoint_relations
(
--     id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    parent_id BIGINT                                  NOT NULL REFERENCES endpoints,
    child_id  BIGINT                                  NOT NULL REFERENCES endpoints,
PRIMARY KEY (parent_id, child_id)
);

CREATE TABLE hibernate_sequences
(
    sequence_name VARCHAR(255) NOT NULL PRIMARY KEY,
    next_val      BIGINT
);


CREATE TABLE volunteers
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    chat_id          BIGINT,
    full_name        VARCHAR(255),
    phone            VARCHAR(255),
    telegram_user_id BIGINT
);

CREATE TABLE bot_users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    chat_id                 BIGINT,
    full_name               VARCHAR(255),
    phone                   VARCHAR(255),
    step_parent             BOOLEAN,
    trial_extended          BOOLEAN,
    trial_extended_informed BOOLEAN,
    trial_failure           BOOLEAN,
    trial_failure_informed  BOOLEAN,
    trial_period            INTEGER,
    trial_start             DATE,
    trial_success           BOOLEAN,
    trial_success_informed  BOOLEAN,
    animal_shelter_id       BIGINT REFERENCES animal_shelters,
    volunteer_id            BIGINT REFERENCES volunteers
);


CREATE TABLE reports
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    behaviour VARCHAR(2047),
    health    VARCHAR(2047),
    ration    VARCHAR(2047),
    user_id   BIGINT REFERENCES bot_users
);

CREATE TABLE report_photos
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    file_name VARCHAR(255),
    report_id BIGINT REFERENCES reports
);

